### ISSUE TITLE
item names containing / do not migrate properly

### ISSUE THREAD

**Issue by leebaylis** [tableau/TabMigrate#1]
Hi, 
Thanks for writing this, it made my life easier! One problem I had was that any data sources or workbooks with a '/' character in the name lose all characters up to and including the last / in the item name upon migration. 

e.g. 

My data source 2013/14 and 2014/15 extracted

becomes simply 

15 extracted

after migration. 

Hope you can fix it, good luck!

Lee

**Comment by benlower** [comment]
@leebaylis thanks for the feedback. sorry about the bug! did you happen to identify the area of the program that is causing the issue?

**Comment by benlower** [comment]
@IvoSalmreTableau I was able to repro this by naming a file "Foo/2015.twbx". I think this might have something to do with the way the REST API cleanses names. In DownloadWorkbooks.cs it gets a collection of SiteWorkbooks which have a ContentUrl which looks like the workbook name but with some 'URL-friendly' cleaning on it. Are we somehow using this ContentUrl as the file name when we save the content locally?

**Comment by IvoSalmreTableau** [comment]
@leebaylis  @benlower 
Just added support for downloading and uploading Workbooks and Data Sources with "/" and "\" in their file names. Because these (and some other) characters are reserved in the Windows file-system, the code needs to "escape" them (i.e. convert them into characters that are allowed). This is now done on download, and the reverse is done on upload.

Updated code & application are on:
https://github.com/tableau/TabMigrate/releases/tag/v1.04

enjoy! -ivo
