### ISSUE TITLE
Issue when downloading site contents

### ISSUE THREAD

**Issue by graham-macleod** [tableau/TabMigrate#3]
Hi. There seems to be a problem when you have a lot of content to download. I had a 254 MB download which took around 931 seconds to successfully download and then all downloads after this failed with a similar error to the one below.

This may be because my login is timing out, but for a site with a lot of content, this may prove difficult.

This may be due to my rest api session timing out (my organisation wants session timeout set at 10 minutes, no arguments) but I was thinking that what I may attempt is to add a Sign Out Class and sign out after every download, and sign back in before every download. Wasteful and tedious, I know, but worth a shot?

```
000,  19/05/2016 20:06:04, Download failed after .6 seconds. https://MYTABURL/api/2.2/sites/d00944ca-80c8-4cd9-a69f-8b46009c4e96/datasources/f70dc130-0914-11e5-805f-03397faea0ed/content
001,  19/05/2016 20:06:04, Error during Datasource download Discovery SPARRA Lowest Level
  https://MYTABURL/api/2.2/sites/d00944ca-80c8-4cd9-a69f-8b46009c4e96/datasources/f70dc130-0914-11e5-805f-03397faea0ed/content
  System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at TableauServerSignedInRequestBase.DownloadFile(String urlDownload, String downloadToDirectory, String baseFilename, DownloadPayloadTypeHelper downloadTypeMapper) in C:\Users\graham01\Documents\Visual Studio 2015\Projects\TabMigrate-master\TabRESTMigrate\RESTHelpers\TableauServerSignedInRequestBase.cs:line 52
   at DownloadDatasources.ExecuteRequest() in C:\Users\graham01\Documents\Visual Studio 2015\Projects\TabMigrate-master\TabRESTMigrate\RESTRequests\DownloadDatasources.cs:line 87
```

Just for a bit more info, I upped the wgserver.session.idle_limit to 60 minutes and the issue does go away, but because we need a 10 minute idle time out in our organisation, this doesn't really rectify the problem. I'm in the process of trying to implement a logout class and will report back if it works.

As a further update, it seems to be a result of downloading lots of data sources from a project, not just a single large data source. If you start downloading 50 data sources from a project, and from the first to the last takes longer than your idle timeout setting on the server, subsequent datasources will fail to download after the timeout ocurrs because your session has exired due to inactivity.

**Comment by graham-macleod** [comment]
Just for a bit more info, I upped the wgserver.session.idle_limit to 60 minutes and the issue does go away, but because we need a 10 minute idle time out in our organisation, this doesn't really rectify the problem. I'm in the process of trying to implement a logout class and will report back if it works.

**Comment by IvoSalmreTableau** [comment]
This is an interesting problem.  I will log this as an issue for our Tableau Server API team, but I suspect a fix is non-trivial.  What I suspect is happening:
1.	Your file download for a specific *.twbx is taking a long time (e.g. 15+ minutes).  
2.	Unlike uploads (which are sent in small/mid-sized chunks), downloads come as a HTTP request/response.  – Thus they are dependent on the speed of your local network, the server, and the client, which have to move all this data in 1 http request/response cycle.
3.	If the single download request/response exceeds you session timeout, the session will expire.  Thus subsequent requests will fail since the session is no longer active.
A work around:  During the download, if you had a separate thread that made simple REST API requests at a frequency below the timeout threshold, this would likely keep the Tableau Server session alive.  – There should be no problem with parallel requests (the download, and the keep alive) occurring at the same time. – If desired, I can look at adding this kind of background keep-alive into the TabMigrare tool.

**Comment by graham-macleod** [comment]
Hi Ivo. I agree, that sounds like they likely cause. I like the parallel thread solution to keep the session alive. I may just set up a request to query sites but limit this to 1 item per request to keep the size small. Thanks for the suggestion. I'll try that this weekend.

**Comment by IvoSalmreTableau** [comment]
Hi there,
Take a look at v1.05.  I just added a “keep alive” checkbox in the export site.  This makes a request every 2 minutes.

**Comment by IvoSalmreTableau** [comment]
(v1.06 -- made one more subtle fix the encoding of messages sent to server)
